noun1 =input("place\n") 
noun2 =input("person\n")
verb1 =input("action\n")
noun3 =input("person\n")
adjective1 =input("describing word\n")
adjective2 =input("describing word\n")
noun3 =input("item\n")
noun4 =input("place\n")
verb2 =input("action\n")
adjective3 =input("describing word\n")
print("Today i went to the " + noun1 + ". There were many " + noun2 + " who were " + verb1 + " too " + noun3 + ". They all looked very " + adjective1 + ". I was very " + adjective2 + ". We went to get " + noun3 + " at " + noun4 + ". After that we all " + verb2 + " " + adjective3 ) 
